import "./globals.css";
import type { Metadata } from "next";
import localFont from 'next/font/local'
import ReactQuery from "@/components/ReactQuery";

const quciksand = localFont({
  src: [
    {
      path: '../public/fonts/Quicksand-Light.ttf',
      weight: '300',
      style: 'light',
    },
    {
      path: '../public/fonts/Quicksand-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Quicksand-Medium.ttf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../public/fonts/Quicksand-SemiBold.ttf',
      weight: '600',
      style: 'semibold',
    },
    {
      path: '../public/fonts/Quicksand-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
  ],
})

export const metadata: Metadata = {
  title: "Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quciksand.className}>
        <ReactQuery>{children}</ReactQuery>
      </body>
    </html>
  );
}
