import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Session } from "next-auth";
import ReactQuery from "@/components/ReactQuery";
import NextAuthProvider from "@/components/NextAuthProvider";
import { ChakraProvider } from "@chakra-ui/react";


interface NextAuthProps {
  children: React.ReactNode;
  session: Session | null | undefined;
}

const poppins = localFont({
  src: [
    {
      path: "../public/fonts/Poppins-Light.ttf",
      weight: "300",
      style: "light",
    },
    {
      path: "../public/fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "../public/fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Agen Sotre",
  description: "Generated by Developer Junior",
};

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ChakraProvider>
          <NextAuthProvider session={session}>
            <ReactQuery>
              {children}
            </ReactQuery>
          </NextAuthProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
